// Generates docs/llms.txt — a machine-readable guide for LLMs/agents landing
// on the deployed report site, per the llmstxt.org convention. Points at the
// same capabilities documented for humans in README.md/API.md/MCP.md: the
// read-only JSON API (no auth, no server) and the local, opt-in MCP server.
// Pure function of already-computed aggregate state — never re-derives it.

const REPO_BLOB_BASE = 'https://github.com/mgifford/vital-core/blob/main';

export function buildLlmsTxt(config, indexEntries) {
  const base = (config.reportBaseUrl || '').replace(/\/+$/, '');
  const abs = (p) => (base ? `${base}${p}` : p);

  const lines = [];
  lines.push('# VITAL Scans');
  lines.push('');
  lines.push(
    '> Continuously-updated accessibility and sustainability reports for ' +
      'government websites, generated by the open source VITAL Scans engine ' +
      '(axe-core + Siteimprove Alfa). The HTML on this site is a rendered ' +
      'view of structured data that is also available directly as a static ' +
      'JSON API — prefer the API over scraping HTML.',
  );
  lines.push('');

  lines.push('## API');
  lines.push('');
  lines.push(
    `- [JSON API index](${abs('/api/v1/index.json')}): all tracked domains, ` +
      'latest week, severity counts, and per-domain links. Static, read-only, no auth.',
  );
  lines.push(
    `- [API catalog](${abs('/.well-known/api-catalog')}): machine-discovery ` +
      'catalog of endpoints, schemas, and agent-oriented entry points.',
  );
  for (const entry of indexEntries) {
    lines.push(
      `- [${entry.key} snapshot](${abs(entry.snapshot_url)}): full history — ` +
        'summary, findings ledger, weekly series, tech associations.',
    );
  }
  lines.push(
    `- [API.md](${REPO_BLOB_BASE}/API.md): full contract, JSON Schemas, retention, and examples.`,
  );
  lines.push('');

  lines.push('## MCP');
  lines.push('');
  lines.push(
    `- [MCP.md](${REPO_BLOB_BASE}/MCP.md): a local, read-only-by-default Model ` +
      'Context Protocol server (stdio, no network port) that lets an ' +
      'MCP-compatible coding client list and inspect findings from this ' +
      'API, and optionally map a finding to a probable local source file. ' +
      'Not hosted at this URL — run it from a checkout of the repository.',
  );
  lines.push('');

  lines.push('## Docs');
  lines.push('');
  lines.push(`- [README](${REPO_BLOB_BASE}/README.md): project overview, design principles, setup.`);
  lines.push('- [Repository](https://github.com/mgifford/vital-core): source, issues, license (AGPL-3.0).');
  lines.push('');

  lines.push('## Notes');
  lines.push('');
  lines.push(
    '- Automated accessibility checkers find roughly 30-40% of WCAG barriers. ' +
      'Use scores and trends to compare and track direction, not as a pass/fail.',
  );
  lines.push(
    '- The API is public and redacted for privacy: URL fragments are stripped ' +
      'and sensitive query parameters are replaced with [REDACTED]. See API.md.',
  );

  return lines.join('\n') + '\n';
}
