vcs:
  type: git
agents:
  available:
  - copilot
  auto_commit: true
project:
  uuid: a7ea4bc9-7cef-4089-9526-34dd8a9f8d46
  slug: vital-core
  node_id: 32b76985e84c
  build_id: 82e325d4-24fb-45f7-9661-a751a957a86f
